create procedure pa_insertaventaenc
@idventa int output,
@idplanta int,
@idcomprador int,
@idcontrato int,
@tara decimal(6,2),
@checktara bit,
@totalpacas int,
@subtotal money,
@castigomic money,
@castigoresistencia money,
@castigouhml money,
@castigoui money,
@deduccion money,
@totalprecio money,
@fechacreacion datetime,
@fechaactualizacion datetime,
@idestatus int
as
begin
	set nocount on 
	merge ventapacasenc as target
	using (select @idventa,
				  @idplanta,
				  @idcomprador,
				  @idcontrato,
				  @tara,
				  @checktara,
				  @totalpacas,
				  @subtotal,
				  @castigomic,
				  @castigoresistencia,
				  @castigouhml,
				  @castigoui,
				  @deduccion,
				  @totalprecio,
				  @fechacreacion,
				  @fechaactualizacion,
				  @idestatus)
	as source (idventa,
				  idplanta,
				  idcomprador,
				  idcontrato,
				  tara,
				  checktara,
				  totalpacas,
				  subtotal,
				  castigomic,
				  castigoresistencia,
				  castigouhml,
				  castigoui,
				  deduccion,
				  totalprecio,
				  fechacreacion,
				  fechaactualizacion,
				  idestatus)
	on (target.idventa = source.idventa)
	when matched then
	update set idplanta = source.idplanta,
			   idcomprador = source.idcomprador,
			   idcontrato = source.idcontrato,
			   tara = source.tara,
			   checktara = source.checktara,
			   totalpacas = source.totalpacas,
			   subtotal = source.subtotal,
			   castigomic = source.castigomic,
			   castigoresistencia = source.castigoresistencia,
			   castigouhml = source.castigouhml,
			   castigoui = source.castigoui,
			   deduccion = source.deduccion,
			   totalprecio = source.totalprecio,
			   fechaactualizacion = source.fechaactualizacion,
			   idestatus = source.idestatus
	when not matched then
	insert (idplanta,
				  idcomprador,
				  idcontrato,
				  tara,
				  checktara,
				  totalpacas,
				  subtotal,
				  castigomic,
				  castigoresistencia,
				  castigouhml,
				  castigoui,
				  deduccion,
				  totalprecio,
				  fechacreacion,
				  fechaactualizacion,
				  idestatus)
	values (source.idplanta,
				  source.idcomprador,
				  source.idcontrato,
				  source.tara,
				  source.checktara,
				  source.totalpacas,
				  source.subtotal,
				  source.castigomic,
				  source.castigoresistencia,
				  source.castigouhml,
				  source.castigoui,
				  source.deduccion,
				  source.totalprecio,
				  source.fechacreacion,
				  source.fechaactualizacion,
				  source.idestatus);
	set @idventa = SCOPE_IDENTITY();
end