alter Procedure Pa_RecalcularVenta
@Baleid bigint,
@IdVenta int,
@PrecioDls decimal(18,4),
@PrecioClase decimal(18,4),
@TipoCambio decimal(18,4),
@PrecioMXN decimal(18,4),
@Kilos decimal(18,4),
@Quintales decimal(18,4),
@CastigoUI decimal(18,4),
@CastigoResistenciaFibra decimal(18,4),
@CastigoMicros decimal(18,4),
@CastigoLargoFibra decimal(18,4),
@CastigoBarkLevel1 decimal(18,4),
@CastigoBarkLevel2 decimal(18,4),
@CastigoPrepLevel1 decimal(18,4),
@CastigoPrepLevel2 decimal(18,4),
@CastigoOtherLevel1 decimal(18,4),
@CastigoOtherLevel2 decimal(18,4),
@CastigoPlasticLevel1 decimal(18,4),
@CastigoPlasticLevel2 decimal(18,4)
as
Update CalculoClasificacion
set    Kilos =@Kilos,
	   Quintales =@Quintales,
	   TipoCambio =@TipoCambio,
	   PrecioMxn =@PrecioMXN,
	   CastigoUIVenta =@CastigoUI,
	   CastigoResistenciaFibraVenta =@CastigoResistenciaFibra,
	   castigoMicVenta =@CastigoMicros,
	   CastigoLargoFibraVenta =@CastigoLargoFibra,
	   CastigoBarkLevel1Venta =@CastigoBarkLevel1,
	   CastigoBarkLevel2Venta =@CastigoBarkLevel2,
	   CastigoPrepLevel1Venta =@CastigoPrepLevel1,
	   CastigoPrepLevel2Venta =@CastigoPrepLevel2,
	   CastigoOtherLevel1Venta =@CastigoOtherLevel1,
	   CastigoOtherLevel2Venta =@CastigoOtherLevel2,
	   CastigoPlasticLevel1Venta =@CastigoPlasticLevel1,
	   CastigoPlasticLevel2Venta =@CastigoPlasticLevel2,
	   PrecioClase =@PrecioClase,
	   PrecioDls =@PrecioDls
where IdVentaEnc = @IdVenta and baleid = @Baleid