CREATE Procedure Sp_ConsultaVenta
@IdVenta int,
@Nombre varchar(max)
as
if @IdVenta = 0 and @Nombre <> ''
begin
	SELECT [vp].[IdVenta]
      ,[vp].[IdContratoAlgodon]
      ,[vp].[IdComprador]
	  ,[co].[Nombre]
      ,[vp].[IdPlanta]
      ,[vp].[IdModalidadVenta]
      ,[vp].[Fecha]
      ,[vp].[TotalPacas]
      ,[vp].[Observaciones]
      ,[vp].[CastigoMicros]
      ,[vp].[CastigoLargoFibra]
      ,[vp].[CastigoResistenciaFibra]
      ,[vp].[InteresPesosMx]
      ,[vp].[InteresDlls]
      ,[vp].[PrecioQuintal]
      ,[vp].[PrecioQuintalBorregos]
      ,[vp].[PrecioDolar]
	  ,[vp].[Subtotal]
	  ,[vp].[CastigoDls]
	  ,[vp].[AnticipoDls]
      ,[vp].[TotalDlls]
	  ,[vp].[TotalPesosMx]
      ,[vp].[IdEstatusVenta]
	  FROM [dbo].[VentaPacas] Vp inner join [dbo].[Compradores] co on [vp].[IdComprador] = [co].[IdComprador]
	  WHERE [co].[Nombre] like '%'+@Nombre+'%'
 end
 else if @IdVenta > 0 and @Nombre = ''
 begin
		SELECT [vp].[IdVenta]
	  ,[vp].[IdContratoAlgodon]
      ,[vp].[IdComprador]
	  ,[co].[Nombre]
      ,[vp].[IdPlanta]
      ,[vp].[IdModalidadVenta]
      ,[vp].[Fecha]
      ,[vp].[TotalPacas]
      ,[vp].[Observaciones]
      ,[vp].[CastigoMicros]
      ,[vp].[CastigoLargoFibra]
      ,[vp].[CastigoResistenciaFibra]
      ,[vp].[InteresPesosMx]
      ,[vp].[InteresDlls]
      ,[vp].[PrecioQuintal]
      ,[vp].[PrecioQuintalBorregos]
      ,[vp].[PrecioDolar]
	  ,[vp].[Subtotal]
	  ,[vp].[CastigoDls]
	  ,[vp].[AnticipoDls]
      ,[vp].[TotalDlls]
	  ,[vp].[TotalPesosMx]
      ,[vp].[IdEstatusVenta]
	  FROM [dbo].[VentaPacas] Vp inner join [dbo].[Compradores] co on [vp].[IdComprador] = [co].[IdComprador]
	  WHERE [vp].[IdVenta] = @IdVenta
end
else
begin
	SELECT [vp].[IdVenta]
	  ,[vp].[IdContratoAlgodon]
      ,[vp].[IdComprador]
	  ,[co].[Nombre]
      ,[vp].[IdPlanta]
      ,[vp].[IdModalidadVenta]
      ,[vp].[Fecha]
      ,[vp].[TotalPacas]
      ,[vp].[Observaciones]
      ,[vp].[CastigoMicros]
      ,[vp].[CastigoLargoFibra]
      ,[vp].[CastigoResistenciaFibra]
      ,[vp].[InteresPesosMx]
      ,[vp].[InteresDlls]
      ,[vp].[PrecioQuintal]
      ,[vp].[PrecioQuintalBorregos]
      ,[vp].[PrecioDolar]
	  ,[vp].[Subtotal]
	  ,[vp].[CastigoDls]
	  ,[vp].[AnticipoDls]
      ,[vp].[TotalDlls]
	  ,[vp].[TotalPesosMx]
      ,[vp].[IdEstatusVenta]
	  FROM [dbo].[VentaPacas] Vp inner join [dbo].[Compradores] co on [vp].[IdComprador] = [co].[IdComprador]
end