Create Procedure sp_ConsultaDetalladaClientes
--declare
@IdCliente int --= 1
as
select IdCliente	,
		Socio	,
		Nombre	,
		IdTipoPersona	,
		Rfc	,
		CurpFisica	,
		CalleFisica	,
		NumeroFisica	,
		IdEstadoFisica	,
		IdMunicipioFisica	,
		ColoniaFisica	,
		CelularFisica	,
		TelefonoFisica	,
		CorreoFisica	,
		ApoderadoFisica	,
		FolioActa	,
		FechaActa	,
		NotarioActa	,
		RegistroPublicoActa	,
		NumeroActa	,
		LibroActa	,
		FolioMercantil	,
		RfcApoderado	,
		CurpApoderado	,
		IneApoderado	,
		NumeroMoral	,
		CalleMoral	,
		IdEstadoMoral	,
		IdMunicipioMoral	,
		ColoniaMoral	,
		TelefonoMoral	,
		CelularMoral	,
		TelefonoApoderado	,
		CelularApoderado	,
		CorreoApoderado	,
		IdEstadoMovilizacion	,
		IdMunicipioMovilizacion	,
		Certificado	,
		Superficie	,
		Predio	,
		IdCuentaDe	,
		IdUsuarioCreacion	,
		FechaCreacion	,
		IdEstatus	
from dbo.Clientes 
where IdEstatus = 1
and   IdCliente = @IdCliente