create PROC Sp_ConsultaConfiguracionParametros
@IdConfiguracion int,
@DireccionIP varchar(15)
as
SELECT [IdConfiguracion]
      ,[NombrePC]
      ,[DireccionIP]
      ,[NombrePuerto]
      ,[IndicadorID]
	  ,[IndicadorModulo]
      ,[IndicadorEntrada]
      ,[IndicadorSalida]
      ,[IndicadorBruto]
      ,[IndicadorTara]
      ,[IndicadorNeto]
      ,[IndicadorPacasBruto]
      ,[IndicadorPacasTara]
      ,[IndicadorPacasNeto]
      ,[PosicionID]
	  ,[PosicionModulo]
      ,[PosicionEntrada]
      ,[PosicionSalida]
      ,[PosicionBruto]
      ,[PosicionTara]
      ,[PosicionNeto]
      ,[PacasPosicionBruto]
      ,[PacasPosicionTara]
      ,[PacasPosicionNeto]
      ,[CaracterID]
	  ,[CaracterModulo]
      ,[CaracterEntrada]
      ,[CaracterSalida]
      ,[CaracterBruto]
      ,[CaracterTara]
      ,[CaracterNeto]
      ,[PacasCaracterBruto]
      ,[PacasCaracterTara]
      ,[PacasCaracterNeto]
FROM CONFIGURACIONPARAMETROS
WHERE DireccionIP = @DireccionIP or idconfiguracion = @IdConfiguracion