CREATE Procedure Sp_ConsultaDatosEmpresa
as
SELECT top 1 [IdDatosEmpresa]
      ,[RazonSocial]
      ,[RFCEmpresa]
      ,[RepresentanteLegal]
      ,[RFCRepresentante]
      ,[Calle]
      ,[NumExt]
      ,[NumInt]
      ,[EntreCalle1]
      ,[EntreCalle2]
      ,[Colonia]
      ,[Referencia]
      ,[Poblacion]
      ,[CodigoPostal]
      ,[Pais]
      ,[Estado]
      ,[Municipio]
      ,[LugarExpedicion]
	  ,[logoempresa]
  FROM [dbo].[DatosEmpresa]