create proc sp_consultaClasesCalculo
@baleid bigint,
@IdPlanta int ,
@IdPaquete int ,
@seleccionar bit = 0
as
select @seleccionar as seleccionar,
	   IdProduccionDetalle,
	   IdOrdenTrabajo,
	   IdPlantaOrigen,
	   IdPaqueteEncabezado,
	   isnull(IdVentaEnc,0) as idventaenc,
	   LotID,
	   BaleID,
	   BaleGroup,
	   Operator,
	   [date],
	   Temperature,
	   Humidity,
	   Amount,
	   UHML,
	   UI,
	   Strength,
	   Elongation,
	   SFI,
	   Maturity,
	   Grade,
	   Moist,
	   Mic,
	   Rd,
	   Plusb,
	   ColorGrade,
	   TrashCount,
	   TrashArea,
	   TrashID,
	   SCI,
	   Nep,
	   UV,
	   FlagTerminadoCompra,
	   FlagTerminadoVenta,
	   EstatusVenta
from ProduccionDetalle a
where a.BaleID = @baleid and a.IdPlantaOrigen = @IdPlanta and a.IdPaqueteEncabezado is null