alter procedure sp_InsertarPaquetesHVIDet
@IdHviDet int,
@IdHviEnc int,
@IdPlantaOrigen int,
@LotID int,
@BaleID bigint,
@BaleGroup varchar(5),
@Operator varchar(25),
@Date datetime,
@Temperature float,
@Humidity float,
@Amount int, 
@UHML float,
@UI float,
@Strength float,
@Elongation float,
@SFI float,
@Maturity float,
@Grade varchar(6),
@Moist float,
@Mic float,
@Rd float,
@Plusb float,
@ColorGrade varchar(4),
@TrashCount int,
@TrashArea float,
@TrashID int,
@SCI int,
@Nep int,
@UV float
as  
update ProduccionDetalle 
SET idhvienc = @IdHviEnc,
	IdPlantaOrigen = @IdPlantaOrigen,
	LotID = @LotID,	
	BaleGroup = @BaleGroup,
	Operator = @Operator,
	[Date] = @Date,
	Temperature = @Temperature,
	Humidity = @Humidity,
	Amount = @Amount,
	UHML = @UHML,
	UI = @UI,
	Strength = @Strength,
	Elongation = @Elongation,
	SFI = @SFI,
	Maturity = @Maturity,
	Grade = @Grade,
	Moist = @Moist,
	Mic = @Mic,
	Rd = @Rd,
	Plusb = @Plusb,
	ColorGrade = @ColorGrade,
	TrashCount = @TrashCount,
	TrashArea = @TrashArea,
	TrashID = @TrashID,
	SCI = @SCI,
	Nep = @Nep,
	UV = @UV
where baleid = @BaleID