 insert into CAT_MUNICIPIO values ('Ahumada',6,1)
 insert into CAT_MUNICIPIO values ('Aldama',6,1)
 insert into CAT_MUNICIPIO values ('Allende',6,1)
 insert into CAT_MUNICIPIO values ('Aquiles Serdán',6,1)
 insert into CAT_MUNICIPIO values ('Ascensión',6,1)
 insert into CAT_MUNICIPIO values ('Bachíniva',6,1)
 insert into CAT_MUNICIPIO values ('Balleza',6,1)
 insert into CAT_MUNICIPIO values ('Batopilas',6,1)
 insert into CAT_MUNICIPIO values ('Bocoyna',6,1)
 insert into CAT_MUNICIPIO values ('Buenaventura',6,1)
 insert into CAT_MUNICIPIO values ('Camargo',6,1)
 insert into CAT_MUNICIPIO values ('Carichí',6,1)
 insert into CAT_MUNICIPIO values ('Casas Grandes',6,1)
 insert into CAT_MUNICIPIO values ('Chihuahua',6,1)
 insert into CAT_MUNICIPIO values ('Chínipas',6,1)
 insert into CAT_MUNICIPIO values ('Coronado',6,1)
 insert into CAT_MUNICIPIO values ('Coyame del Sotol',6,1)
 insert into CAT_MUNICIPIO values ('Cuauhtémoc',6,1)
 insert into CAT_MUNICIPIO values ('Cusihuiriachi',6,1)
 insert into CAT_MUNICIPIO values ('Delicias',6,1)
 insert into CAT_MUNICIPIO values ('Belisario Domínguez',6,1)
 insert into CAT_MUNICIPIO values ('El Tule',6,1)
 insert into CAT_MUNICIPIO values ('Galeana',6,1)
 insert into CAT_MUNICIPIO values ('Gómez Farías',6,1)
 insert into CAT_MUNICIPIO values ('Gran Morelos',6,1)
 insert into CAT_MUNICIPIO values ('Guachochi',6,1)
 insert into CAT_MUNICIPIO values ('Guadalupe',6,1)
 insert into CAT_MUNICIPIO values ('Guadalupe y Calvo',6,1)
 insert into CAT_MUNICIPIO values ('Guazapares',6,1)
 insert into CAT_MUNICIPIO values ('Guerrero',6,1)
 insert into CAT_MUNICIPIO values ('Hidalgo del Parral',6,1)
 insert into CAT_MUNICIPIO values ('Huejotitán',6,1)
 insert into CAT_MUNICIPIO values ('Ignacio Zaragoza',6,1)
 insert into CAT_MUNICIPIO values ('Janos',6,1)
 insert into CAT_MUNICIPIO values ('Jiménez',6,1)
 insert into CAT_MUNICIPIO values ('Juárez',6,1)
 insert into CAT_MUNICIPIO values ('Julimes',6,1)
 insert into CAT_MUNICIPIO values ('La Cruz',6,1)
 insert into CAT_MUNICIPIO values ('López',6,1)
 insert into CAT_MUNICIPIO values ('Madera',6,1)
 insert into CAT_MUNICIPIO values ('Maguarichi',6,1)
 insert into CAT_MUNICIPIO values ('Manuel Benavides',6,1)
 insert into CAT_MUNICIPIO values ('Matachí',6,1)
 insert into CAT_MUNICIPIO values ('Matamoros',6,1)
 insert into CAT_MUNICIPIO values ('Meoqui',6,1)
 insert into CAT_MUNICIPIO values ('Morelos',6,1)
 insert into CAT_MUNICIPIO values ('Moris',6,1)
 insert into CAT_MUNICIPIO values ('Namiquipa',6,1)
 insert into CAT_MUNICIPIO values ('Nonoava',6,1)
 insert into CAT_MUNICIPIO values ('Nuevo Casas Grandes',6,1)
 insert into CAT_MUNICIPIO values ('Ocampo',6,1)
 insert into CAT_MUNICIPIO values ('Ojinaga',6,1)
 insert into CAT_MUNICIPIO values ('Praxedis G. Guerrero',6,1)
 insert into CAT_MUNICIPIO values ('Riva Palacio',6,1)
 insert into CAT_MUNICIPIO values ('Rosales',6,1)
 insert into CAT_MUNICIPIO values ('Rosario',6,1)
 insert into CAT_MUNICIPIO values ('San Francisco de Borja',6,1)
 insert into CAT_MUNICIPIO values ('San Francisco de Conchos',6,1)
 insert into CAT_MUNICIPIO values ('San Francisco del Oro',6,1)
 insert into CAT_MUNICIPIO values ('Santa Bárbara',6,1)
 insert into CAT_MUNICIPIO values ('Santa Isabel',6,1)
 insert into CAT_MUNICIPIO values ('Satevó',6,1)
 insert into CAT_MUNICIPIO values ('Saucillo',6,1)
 insert into CAT_MUNICIPIO values ('Temósachic',6,1)
 insert into CAT_MUNICIPIO values ('Urique',6,1)
 insert into CAT_MUNICIPIO values ('Uruachi',6,1)
 insert into CAT_MUNICIPIO values ('Valle de Zaragoza',6,1)