CREATE TABLE [dbo].[CalculoClasificacion](
	[IdCalculoClasificacion] [int] primary key IDENTITY(1,1) NOT NULL,
	[IdPaqueteEncabezado] [int] NOT NULL,
	[IdHviDetalle] [int] NOT NULL,
	[IdOrdenTrabajo] [int] NOT NULL,
	[BaleID] [int] NULL,
	[BaleGroup] [varchar](5) NULL,
	[Operator] [varchar](25) NULL,
	[Date] [datetime] NULL,
	[Temperature] [float] NULL,
	[Humidity] [float] NULL,
	[Amount] [int] NULL,
	[UHML] [float] NULL,
	[UI] [float] NULL,
	[Strength] [float] NULL,
	[Elongation] [float] NULL,
	[SFI] [float] NULL,
	[Maturity] [float] NULL,
	[Grade] [varchar](6) NULL,
	[Moist] [float] NULL,
	[Mic] [float] NULL,
	[Rd] [float] NULL,
	[Plusb] [float] NULL,
	[ColorGrade] [varchar](4) NULL,
	[TrashCount] [int] NULL,
	[TrashArea] [float] NULL,
	[TrashID] [int] NULL,
	[SCI] [int] NULL,
	[Nep] [int] NULL,
	[UV] [float] NULL,
	[FlagTerminado] [bit] NULL,
	[EstatusCompra] [int] NULL,
	[Seleccion] [bit] null
) 
