CREATE TABLE com_producciondet
(
[IdProduccionDetalle] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
[IdProduccion] [int] NULL,
[IdTemporada] [int] NULL,
[IdPredio] [int] NULL,
[IdHviEnc] [int] NULL,
[IdOrdenTrabajo] [int] NULL,
[IdPlantaOrigen] [int] NULL,
[IdPaqueteEncabezado] [int] NULL,
[IdAsignacionEnc] [int] NULL,
[IdCompraEnc] [int] NULL,
[IdVentaEnc] [int] NULL,
[IdLote] [int] NULL,
[IdEmbarqueEncabezado] [int] NULL,
[IdSalidaEncabezado] [int] NULL,
[pepena] [bit] NULL,
[revisada] [bit] NULL,
[Kilos] [float] NOT NULL,
[Libras] [float] NULL,
[Quintales] [float] NULL,
[KilosCompra] [float] NOT NULL,
[LibrasCompra] [float] NULL,
[QuintalesCompra] [float] NULL,
[KilosVenta] [float] NOT NULL,
[LibrasVenta] [float] NULL,
[QuintalesVenta] [float] NULL,
[BandExiste] [bit] NULL,
[IdTurno] [int] NULL,
[Fecha] [datetime] NULL,
[LotID] [int] NULL,
[BaleID] [bigint] NULL UNIQUE,
[BaleGroup] [varchar](5) NULL,
[Operator] [varchar](25) NULL,
[Date] [datetime] NULL,
[Temperature] [float] NULL,
[Humidity] [float] NULL,
[Amount] [float] NULL,
[UHML] [float] NULL,
[UI] [float] NULL,
[Strength] [float] NULL,
[Elongation] [float] NULL,
[SFI] [float] NULL,
[Maturity] [float] NULL,
[Grade] [varchar](6) NULL,
[Moist] [float] NULL,
[Mic] [float] NULL,
[Rd] [float] NULL,
[Plusb] [float] NULL,
[ColorGrade] [varchar](4) NULL,
[TrashCount] [int] NULL,
[TrashArea] [float] NULL,
[TrashID] [int] NULL,
[SCI] [int] NULL,
[Nep] [int] NULL,
[UV] [float] NULL,
[PrecioClaseCompra] [float] NULL,
[PrecioPacaCompra] [float] NULL,
[PrecioClaseVenta] [float] NULL,
[PrecioPacaVenta] [float] NULL,
[castigoMicCompra] [float] NULL,
[CastigoLargoFibraCompra] [float] NULL,
[CastigoResistenciaFibraCompra] [float] NULL,
[CastigoUICompra] [float] NULL,
[castigoMicVenta] [decimal](18, 4) NULL,
[CastigoLargoFibraVenta] [decimal](18, 4) NULL,
[CastigoResistenciaFibraVenta] [decimal](18, 4) NULL,
[CastigoUIVenta] [decimal](18, 4) NULL
)