CREATE TABLE [dbo].[CompraPacas](
	[IdCompra] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[IdContratoAlgodon] [int] NOT NULL,
	[IdProductor] [int] NOT NULL,
	[IdPlanta] [int] NOT NULL,
	[IdModalidadCompra] [int] NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[TotalPacas] [int] NOT NULL,
	[Observaciones] [varchar](500) NOT NULL,
	[CastigoMicros] [float] NOT NULL,
	[CastigoLargoFibra] [float] NOT NULL,
	[CastigoResistenciaFibra] [float] NOT NULL,
	[TotalPesosMx] [float] NOT NULL,
	[TotalDlls] [int] NOT NULL,
	[InteresPesosMx] [float] NOT NULL,
	[InteresDlls] [float] NOT NULL,
	[PrecioQuintal] [float] NOT NULL,
	[PrecioQuintalBorregos] [float] NOT NULL,
	[PrecioDolar] [float] NOT NULL,
	[Descuento] [float] NOT NULL,
	[Total] [float] NOT NULL,
	[IdEstatusCompra] [int] NOT NULL,
	[IdUsuarioCreacion] [int] NOT NULL,
	[FechaCreacion] [datetime] NOT NULL,
	[IdUsuarioActualizacion] [int] NOT NULL,
	[FechaActualizacion] [datetime] NOT NULL,
	)


