CREATE TABLE PaqueteEncabezado(
	[IdPaquete] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[LotID] [int] NULL unique,
	[IdPlanta] [int] NULL,
	[idComprador] [int] NULL,
	[IdClase] [int] NULL,
	[CantidadPacas] [int] NULL,
	[Descripcion] [varchar](20) NULL,
	[Entrega] [int] NULL,
	[chkrevisado] [bit] NULL,
	[IdEstatus] [int] NULL,
	[IdUsuarioCreacion] [int] NULL,
	[FechaCreacion] [datetime] NULL,
	[IdUsuarioActualizacion] [int] NULL,
	[FechaActualizacion] [datetime] NULL)