Create table ParametrosContratoCompra
(
IdParametroContrato int identity(1,1) primary key,
IdContratoCompra int,
CheckMicros bit,
IdModoMicros int,
CheckLargo bit,
IdModoLargoFibra int,
CheckResistencia bit,
IdModoResistencia int,
CheckUniformidad bit,
IdModoUniformidad int,
CheckBark bit,
IdModoBark int,
CheckBarkLevel1 bit,
CheckBarkLevel2 bit,
CheckPrep bit,
IdModoPrep int,
CheckPrepLevel1 bit,
CheckPrepLevel2 bit,
CheckOther bit,
IdModoOther int,
CheckOtherLevel1 bit,
CheckOtherLevel2 bit,
CheckPlastic bit,
IdModoPlastic int,
CheckPlasticLevel1 bit,
CheckPlasticLevel2 bit
)