Create Procedure sp_InsertarCliente
@IdCliente	int	output,
@Socio	varchar(100)	,
@Nombre	varchar(100)	,
@IdTipoPersona	int	,
@Rfc	varchar(20)	,
@CurpFisica	varchar(20)	,
@CalleFisica	varchar(30)	,
@NumeroFisica	varchar(10)	,
@IdEstadoFisica	int	,
@IdMunicipioFisica	int	,
@ColoniaFisica	varchar(50)	,
@CelularFisica	varchar(15)	,
@TelefonoFisica	varchar(15)	,
@CorreoFisica	varchar(50)	,
@ApoderadoFisica	varchar(50)	,
@FolioActa	varchar(30)	,
@FechaActa	datetime	,
@NotarioActa	varchar(30)	,
@RegistroPublicoActa	varchar(30)	,
@NumeroActa	varchar(30)	,
@LibroActa	varchar(30)	,
@FolioMercantil	varchar(30)	,
@RfcApoderado	varchar(20)	,
@CurpApoderado	varchar(20)	,
@IneApoderado	varchar(20)	,
@NumeroMoral varchar(10),
@CalleMoral	varchar(30)	,
@IdEstadoMoral	int	,
@IdMunicipioMoral	int	,
@ColoniaMoral varchar(50)	,
@TelefonoMoral	varchar(15)	,
@CelularMoral	varchar(15)	,
@TelefonoApoderado	varchar(15)	,
@CelularApoderado	varchar(15)	,
@CorreoApoderado	varchar(50)	,
@IdEstadoMovilizacion	int	,
@IdMunicipioMovilizacion	int	,
@Certificado	varchar(30)	,
@Superficie	float	,
@Predio	varchar(30)	,
@IdCuentaDe	int	,
@IdUsuarioCreacion	int	,
@FechaCreacion	datetime	,
@IdEstatus	int	

as
begin
set nocount on
merge [dbo].[Clientes] as target
using (select @IdCliente	,
			@Socio	,
			@Nombre	,
			@IdTipoPersona	,
			@Rfc	,
			@CurpFisica	,
			@CalleFisica	,
			@NumeroFisica	,
			@IdEstadoFisica	,
			@IdMunicipioFisica	,
			@ColoniaFisica	,
			@CelularFisica	,
			@TelefonoFisica	,
			@CorreoFisica	,
			@ApoderadoFisica	,
			@FolioActa	,
			@FechaActa	,
			@NotarioActa	,
			@RegistroPublicoActa	,
			@NumeroActa	,
			@LibroActa	,
			@FolioMercantil	,
			@RfcApoderado	,
			@CurpApoderado	,
			@IneApoderado	,
			@NumeroMoral	,
			@CalleMoral	,
			@IdEstadoMoral	,
			@IdMunicipioMoral	,
			@ColoniaMoral	,
			@TelefonoMoral	,
			@CelularMoral	,
			@TelefonoApoderado	,
			@CelularApoderado	,
			@CorreoApoderado	,
			@IdEstadoMovilizacion	,
			@IdMunicipioMovilizacion	,
			@Certificado	,
			@Superficie	,
			@Predio	,
			@IdCuentaDe	,
			@IdUsuarioCreacion	,
			@FechaCreacion	,
			@IdEstatus) AS SOURCE 
			  (IdCliente	,
				Socio	,
				Nombre	,
				IdTipoPersona	,
				Rfc	,
				CurpFisica	,
				CalleFisica	,
				NumeroFisica	,
				IdEstadoFisica	,
				IdMunicipioFisica	,
				ColoniaFisica	,
				CelularFisica	,
				TelefonoFisica	,
				CorreoFisica	,
				ApoderadoFisica	,
				FolioActa	,
				FechaActa	,
				NotarioActa	,
				RegistroPublicoActa	,
				NumeroActa	,
				LibroActa	,
				FolioMercantil	,
				RfcApoderado	,
				CurpApoderado	,
				IneApoderado	,
				NumeroMoral,
				CalleMoral	,
				IdEstadoMoral	,
				IdMunicipioMoral	,
				ColoniaMoral	,
				TelefonoMoral	,
				CelularMoral	,
				TelefonoApoderado	,
				CelularApoderado	,
				CorreoApoderado	,
				IdEstadoMovilizacion	,
				IdMunicipioMovilizacion	,
				Certificado	,
				Superficie	,
				Predio	,
				IdCuentaDe	,
				IdUsuarioCreacion	,
				FechaCreacion	,
				IdEstatus	)
ON (target.IdCliente = SOURCE.IdCliente)
WHEN MATCHED THEN
UPDATE SET Socio = source.Socio,
			Nombre = source.Nombre,
			IdTipoPersona = source.IdTipoPersona,
			Rfc = source.Rfc,
			CurpFisica = source.CurpFisica,
			CalleFisica = source.CalleFisica,
			NumeroFisica = source.NumeroFisica,
			IdEstadoFisica = source.IdEstadoFisica,
			IdMunicipioFisica = source.IdMunicipioFisica,
			ColoniaFisica = source.ColoniaFisica,
			CelularFisica = source.CelularFisica,
			TelefonoFisica = source.TelefonoFisica,
			CorreoFisica = source.CorreoFisica,
			ApoderadoFisica = source.ApoderadoFisica,
			FolioActa = source.FolioActa,
			FechaActa = source.FechaActa,
			NotarioActa = source.NotarioActa,
			RegistroPublicoActa = source.RegistroPublicoActa,
			NumeroActa = source.NumeroActa,
			LibroActa = source.LibroActa,
			FolioMercantil = source.FolioMercantil,
			RfcApoderado = source.RfcApoderado,
			CurpApoderado = source.CurpApoderado,
			IneApoderado = source.IneApoderado,
			NumeroMoral = source.NumeroMoral,
			CalleMoral = source.CalleMoral,
			IdEstadoMoral = source.IdEstadoMoral,
			IdMunicipioMoral = source.IdMunicipioMoral,
			ColoniaMoral = source.ColoniaMoral,
			TelefonoMoral = source.TelefonoMoral,
			CelularMoral = source.CelularMoral,
			TelefonoApoderado = source.TelefonoApoderado,
			CelularApoderado = source.CelularApoderado,
			CorreoApoderado = source.CorreoApoderado,
			IdEstadoMovilizacion = source.IdEstadoMovilizacion,
			IdMunicipioMovilizacion = source.IdMunicipioMovilizacion,
			Certificado = source.Certificado,
			Superficie = source.Superficie,
			Predio = source.Predio,
			IdCuentaDe = source.IdCuentaDe,
			IdUsuarioCreacion = source.IdUsuarioCreacion,
			FechaCreacion = source.FechaCreacion,
			IdEstatus = source.IdEstatus

WHEN NOT MATCHED THEN
INSERT (Socio	,
		Nombre	,
		IdTipoPersona	,
		Rfc	,
		CurpFisica	,
		CalleFisica	,
		NumeroFisica	,
		IdEstadoFisica	,
		IdMunicipioFisica	,
		ColoniaFisica	,
		CelularFisica	,
		TelefonoFisica	,
		CorreoFisica	,
		ApoderadoFisica	,
		FolioActa	,
		FechaActa	,
		NotarioActa	,
		RegistroPublicoActa	,
		NumeroActa	,
		LibroActa	,
		FolioMercantil	,
		RfcApoderado	,
		CurpApoderado	,
		IneApoderado	,
		NumeroMoral	,
		CalleMoral	,
		IdEstadoMoral	,
		IdMunicipioMoral	,
		ColoniaMoral	,
		TelefonoMoral	,
		CelularMoral	,
		TelefonoApoderado	,
		CelularApoderado	,
		CorreoApoderado	,
		IdEstadoMovilizacion	,
		IdMunicipioMovilizacion	,
		Certificado	,
		Superficie	,
		Predio	,
		IdCuentaDe	,
		IdUsuarioCreacion	,
		FechaCreacion	,
		IdEstatus	
)
        VALUES ( source.Socio,
				 source.Nombre,
				 source.IdTipoPersona,
				 source.Rfc,
				 source.CurpFisica,
				 source.CalleFisica,
				 source.NumeroFisica,
				 source.IdEstadoFisica,
				 source.IdMunicipioFisica,
				 source.ColoniaFisica,
				 source.CelularFisica,
				 source.TelefonoFisica,
				 source.CorreoFisica,
				 source.ApoderadoFisica,
				 source.FolioActa,
				 source.FechaActa,
				 source.NotarioActa,
				 source.RegistroPublicoActa,
				 source.NumeroActa,
				 source.LibroActa,
				 source.FolioMercantil,
				 source.RfcApoderado,
				 source.CurpApoderado,
				 source.IneApoderado,
				 source.NumeroMoral,
				 source.CalleMoral,
				 source.IdEstadoMoral,
				 source.IdMunicipioMoral,
				 source.ColoniaMoral,
				 source.TelefonoMoral,
				 source.CelularMoral,
				 source.TelefonoApoderado,
				 source.CelularApoderado,
				 source.CorreoApoderado,
				 source.IdEstadoMovilizacion,
				 source.IdMunicipioMovilizacion,
				 source.Certificado,
				 source.Superficie,
				 source.Predio,
				 source.IdCuentaDe,
				 source.IdUsuarioCreacion,
				 source.FechaCreacion,
				 source.IdEstatus);
		SET @IdCliente = SCOPE_IDENTITY()
END
RETURN @IdCliente
