Create Procedure Sp_ConsultaVentaPacas
@IdVenta int
as
SELECT [IdVenta]
      ,[IdContratoAlgodon]
      ,[IdComprador]
      ,[IdPlanta]
      ,[IdModalidadVenta]
      ,[Fecha]
      ,[TotalPacas]
      ,[Observaciones]
      ,[CastigoMicros]
      ,[CastigoLargoFibra]
      ,[CastigoResistenciaFibra]
      ,[CastigoUI]
      ,[CastigoBarkLevel1]
      ,[CastigoBarkLevel2]
      ,[CastigoPrepLevel1]
      ,[CastigoPrepLevel2]
      ,[CastigoOtherLevel1]
      ,[CastigoOtherLevel2]
      ,[CastigoPlasticLevel1]
      ,[CastigoPlasticLevel2]
      ,[IdUnidadPeso]
      ,[ValorConversion]
      ,[Unidad]
      ,[InteresPesosMx]
      ,[InteresDlls]
      ,[PrecioQuintal]
      ,[PrecioQuintalBorregos]
      ,[PrecioDolar]
      ,[Subtotal]
      ,[CastigoDls]
      ,[AnticipoDls]
      ,[TotalDlls]
      ,[TotalPesosMx]
      ,[IdEstatusVenta]
  FROM [dbo].[VentaPacas]
  WHERE [IdVenta] = @IdVenta