CREATE TABLE [dbo].[Produccion1](
	[IdProduccion] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[IdPlantaOrigen] [int] NULL,
	[IdPlantaDestino] [int] NULL,
	[IdOrdenTrabajo] [int] NULL,
	[Tipo] [varchar](20) NULL,
	[IdCliente] [int] NULL,
	[Fecha] [datetime] NULL,
	[IdEstatus] [int] NULL,
	[TotalHueso] [float] NULL,
	[Pacas] [int] NULL,
	[PlumaPacas] [float] NULL,
	[PlumaBorregos] [float] NULL,
	[Pluma] [float] NULL,
	[Semilla] [float] NULL,
	[Merma] [float] NULL,
	[Borra] [float] NULL,
	[PorcentajePluma] [float] NULL,
	[PorcentajeSemilla] [float] NULL,
	[PorcentajeMerma] [float] NULL,
	[IdUsuarioCreacion] [int] NULL,
	[FechaCreacion] [datetime] NULL,
	[IdUsuarioActualizacion] [int] NULL,
	[FechaActualizacion] [datetime] NULL,
) 
GO
insert into produccion1
select
pr.IdPlantaOrigen	,
pr.IdPlantaDestino	,
pr.IdOrdenTrabajo	,
PR.Tipo	,
PR.IdCliente	,
PR.Fecha	,
PR.IdEstatus	,
PR.TotalHueso	,
count(pd.FolioCIA) AS Pacas	,
isnull(sum(pd.kilos),0) as PlumaPacas	,
PR.PlumaBorregos	,
PR.Pluma	,
PR.Semilla	,
PR.Merma	,
PR.Borra	,
PR.PorcentajePluma	,
PR.PorcentajeSemilla	,
PR.PorcentajeMerma	,
PR.IdUsuarioCreacion	,
PR.FechaCreacion	,
PR.IdUsuarioActualizacion	,
PR.FechaActualizacion
FROM produccion pr left join ProduccionDetalle pd
							on pr.IdPlantaOrigen = pd.IdPlantaOrigen and
							   pr.IdOrdenTrabajo = pd.IdOrdenTrabajo
							group by pd.IdProduccion,pd.IdOrdenTrabajo,PR.IdPlantaOrigen , PR.IdPlantaDestino,PR.IdOrdenTrabajo,PR.Tipo,PR.IdCliente,PR.Fecha,PR.IdEstatus,PR.TotalHueso,PR.PlumaBorregos	,
PR.Pluma	,
PR.Semilla	,
PR.Merma	,
PR.Borra	,
PR.PorcentajePluma	,
PR.PorcentajeSemilla	,
PR.PorcentajeMerma	,
PR.IdUsuarioCreacion	,
PR.FechaCreacion	,
PR.IdUsuarioActualizacion	,
PR.FechaActualizacion,
pr.IdProduccion
							order by pr.IdProduccion