drop table ContratoVenta
go
CREATE TABLE [dbo].[ContratoVenta](
	[IdContratoAlgodon] [int] IDENTITY(1,1) NOT NULL primary key,
	[IdComprador] [int] NULL,
	[Pacas] [int] NULL,
	[PacasCompradas] [INT] NULL,
    [PacasDisponibles] [INT] NULL,
	[PrecioQuintal] [float] NULL,
	[IdUnidadPeso] [int] NULL,
	[ValorConversion] [float] NULL,
	[Puntos] [float] NULL,
	[FechaLiquidacion] [datetime] NULL,
	[Presidente] [varchar](100) NULL,
	[IdModalidadCompra] [int] NULL,
	[Temporada] [varchar](20) NULL,
	[PrecioSM] [float] NULL,
	[PrecioMP] [float] NULL,
	[PrecioM] [float] NULL,
	[PrecioSLMP] [float] NULL,
	[PrecioSLM] [float] NULL,
	[PrecioLMP] [float] NULL,
	[PrecioLM] [float] NULL,
	[PrecioSGO] [float] NULL,
	[PrecioGO] [float] NULL,
	[PrecioO] [float] NULL,
	[IdEstatus] [int] NULL,
	[IdUsuarioCreacion] [int] NULL,
	[FechaCreacion] [datetime] NULL,
	[IdUsuarioActualizacion] [int] NULL,
	[FechaActualizacion] [datetime] NULL
)