Public Class VentaPacasContrato
    Inherits Tarjeta
    Public IdVenta As String
    Public IdContrato As Integer
    Public IdComprador As Integer
    Public IdProductor As Integer
    Public IdPlanta As Integer
    Public IdModalidadVenta As Integer
    Public FechaVenta As DateTime
    Public TotalPacas As Integer
    Public Observaciones As String
    Public CastigoMicros As Double
    Public CastigoLargoFibra As Double
    Public CastigoResistenciaFibra As Double
    Public CastigoUI As Double
    Public CastigoBarkLevel1 As Double
    Public CastigoBarkLevel2 As Double
    Public CastigoPrepLevel1 As Double
    Public CastigoPrepLevel2 As Double
    Public CastigoOtherLevel1 As Double
    Public CastigoOtherLevel2 As Double
    Public CastigoPlasticLevel1 As Double
    Public CastigoPlasticLevel2 As Double
    Public IdUnidadPeso As Integer
    Public ValorConversion As Double
    Public Unidad As Integer
    Public InteresPesosMx As Double
    Public InteresDlls As Double
    Public PrecioQuintal As Double
    Public PrecioQuintalBorregos As Double
    Public SubTotal As Double
    Public CastigoDls As Double
    Public AnticipoDls As Double
    Public PacasInicio As Integer
    Public PacasFin As Integer
    Public PrecioDolar As Double
    Public FacturaVenta As String
    Public TotalDlls As Double
    Public TotalPesosMx As Double
    Public NoPacas As Integer
    Public InicioPaca As Integer
    Public FinPaca As Integer
    Public Clase As String
    Public IdPaquete As Integer
    Public IdEstatusVenta As Integer
    Public NombreComprador As String
    Public PacasVendidas As Integer
    Public PacasDisponibles As Integer
    'Tablas de Castigos y modalidad compra
    Public TablaCastigoMicros As DataTable
    Public TablaCastigoLargoFibra As DataTable
    Public TablaCastigoResistenciaFibra As DataTable
    Public TablaModalidadCompra As DataTable
End Class
